[package]
name = "counter-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = { workspace = true }
once_cell = { workspace = true }
reratui = { workspace = true }
reratui-hooks = { workspace = true }
tokio = { workspace = true }
